# DataSource Config
spring:
  application:
    name: langbei
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/huifriend?serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/hui_friend?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池最大连接数，默认是 10
      maximum-pool-size: 60
    #session失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    port: 6379
    host: 192.168.1.236
    database: 0
    password: lilishop
  elasticsearch:
    uris: http://192.168.1.236:9200
  rabbitmq:
    host: 192.168.1.236
    port: 5672
    username: admin
    password: admin
server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        #        domain: bytes-stream.net
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 #逻辑已删除
      logic-not-delete-value: 0 #逻辑未删除
aliyun:
  oss:
    file:
      endpoint: XXXXXXX.com
      keyid: XXXXXX
      keysecret: XXXXXX
      bucketname: XXXXXX
